import Head from "next/head";

import Footer from "../components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Statistikk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-green-400">
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </div>
      <Footer />
    </div>
  );
}
