import Head from 'next/head';

import client from 'util/client.js';
import Layout from 'components/layout';
import Heading from 'components/heading';
import BlockContent from 'components/blockContent';
import SiteList from 'components/siteList';
import CategoryRefList from '/components/categoryRefList';
import { footerQuery, blockContentQuery, menuQuery } from 'util/queries';
export default function Home({
  menuData = {},
  pageData = {},
  footerData = {},
  siteList = [],
  preview = false
}) {
  const { title, categoryList, blockContent } = pageData;

  return (
    <div>
      <Head>
        <title>Statistikk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout footerData={footerData} menuData={menuData}>
        <Heading title={title} />

        <BlockContent blockContent={blockContent || []} />
        <CategoryRefList categoryList={categoryList || []} />
        <SiteList siteList={siteList || []}/>
      </Layout>
    </div>
  );
}

export async function getStaticProps({ preview = false }) {
  const query = `{"siteList": *[_type=="site"]{title, slug, _type, _id, "category": categoryReference->{title}}, "pageData": *[_type == 'frontPage' && _id == 'frontPage' && !(_id in path("drafts.**"))][0]{title, ${blockContentQuery}, "categoryList": categoryRefList[]->{_id, _type, title, slug, lede, path, ... }, ...}, ${footerQuery}, ${menuQuery} }`;
  const data = await client.fetch(query);
  const { pageData = {}, footerData = {}, siteList = [], menuData = {} } = data;
  return {
    props: {
      pageData: pageData,
      footerData: footerData,
      menuData: menuData,
      siteList: siteList
    },
    revalidate: 200
  };
}
