name: Validate web code

on:
  push: {}

  pull_request:
    paths:
      - web

env:
  working-directory: web

jobs:
  # check-lint:
  #   name: Check lint

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Install Node.js dependencies
  #       uses: bahmutov/npm-install@v1
  #       with:
  #         working-directory: ${{env.working-directory}}

  #     - name: Check lint
  #       run: npm run lint
  #       working-directory: ${{ env.working-directory }}

  check-format:
    name: Check format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.working-directory}}

      - name: Check format
        run: npm run format:check
        working-directory: ${{ env.working-directory }}

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.working-directory}}

      - name: Check format
        run: npm run build
        working-directory: ${{ env.working-directory }}
